export const KEYPRESS_UP = "KEYPRESS_UP";
export const KEYPRESS_DOWN = "KEYPRESS_DOWN";
export const KEYPRESS_LEFT = "KEYPRESS_LEFT";
export const KEYPRESS_RIGHT = "KEYPRESS_RIGHT";
export const KEYPRESS_ARROW = "KEYPRESS_ARROW";
export const SET_NAME = "SET_NAME";
